Added event listener for Woocommerce Related Accessories AJAX load.
netzstrategen/wordpress-gallerya pull request #86
Opened 2022-06-15 11:26 UTC by alinistrate

### Ticket
- [Load related accessories with AJAX with refreshing page](https://app.asana.com/0/1202197213338206/1202345495275050)

2022-08-03 07:15 UTC, sun requested changes

2022-08-03 07:15 UTC, sun commented on assets/scripts/script.js
> +      // Adds slide navigation through variation thumbnails for variable products
This is a good idea to do in general, but can you move the code back up to its original position in the file?

2022-08-03 07:15 UTC, sun commented on assets/scripts/script.js
> +    // Reinitialize slider for Woocommerce Related Accessories
The event actually doesn't seem to be related to related-accessories, so we should drop its name from the comment here.

2025-11-20 10:23 UTC, fabianmarz commented
Closing since stale and no upstream ticket linked. Please re-open if it's still relevant.

2025-11-20 10:23 UTC, closed without merging